### ISSUE TITLE
A way to opt out after createGtm

### ISSUE THREAD

**Issue by Hiroshiba** [gtm-support/vue-gtm#105]
## Request / Idea

I would like to be able to configure the user to not send any information from the application.
To do this, we need to prevent sending data to GTM in some way.

Currently, vue-gtm can be opted out by setting `enable` of `createGtm` to `false`, but this requires the user to reload once.
I would like to have a way to delay opting out by code without reloading.

## Additional Context

https://github.com/VOICEVOX/voicevox/pull/497

**Comment by Shinigami92** [comment]
I think this is possible by just using `enable`

https://github.com/gtm-support/core/blob/23ab0f120b41aaf17d829f6fb30e2d862facc9c3/src/gtm-support.ts#L134
https://github.com/gtm-support/core/blob/23ab0f120b41aaf17d829f6fb30e2d862facc9c3/src/gtm-support.ts#L153
https://github.com/gtm-support/core/blob/23ab0f120b41aaf17d829f6fb30e2d862facc9c3/src/gtm-support.ts#L194

These functions only triggers if the plugin is enabled, otherwise they may only log stuff.

**Comment by Shinigami92** [comment]
No response for nearly half a year
Please reopen if needed or directly create a PR
